import type { Metadata } from "next";
import "./globals.css";
import Rodape from "@/components/Rodape/Rodape";
import Cabecalho from "@/components/Cabecalho/Cabecalho";


export const metadata: Metadata = {
  title: "Tarefas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      
      <body className="flex-col min-h-screen"> 
        <Cabecalho/>
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap"
          rel="stylesheet"
        />
          {children}
        <Rodape/>
      </body>
      
    
    </html>
  );
}
